apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: permission-redis-sts
spec:
  selector:
    matchLabels:
      app: permission-redis-dep
  serviceName: permission-redis
  replicas: 2
  template:
    metadata:
      labels:
        app: permission-redis-dep
    spec:
      containers:
      - name: permission-redis-dep
        image: redis:7.0.8
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: data
          mountPath: /data
        env:
        - name: REDIS_USERNAME
          valueFrom:
            secretKeyRef:
              name: permission-redis-secret
              key: permission_redis_username
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: permission-redis-secret
              key: permission_redis_password
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 1Gi
