apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-dep
spec:
  selector:
    matchLabels:
      app: content-dep
  template:
    metadata:
      labels:
        app: content-dep
    spec:
      containers:
      - name: content-dep
        image: thatcoldtoast/bird-api-content
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 443
        env:
        - name: NEO4J_URI
          valueFrom:
            secretKeyRef:
              key: neo4j_uri
        - name: NEO4J_PORT
          valueFrom:
            secretKeyRef:
              key: neo4j_port
        - name: NEO4J_USERNAME
          valueFrom:
            secretKeyRef:
              key: neo4j_username
        - name: NEO4J_PASSWORD
          valueFrom:
            secretKeyRef:
              key: neo4j_password
