apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-dep
spec:
  selector:
    matchLabels:
      app: content-dep
  template:
    metadata:
      labels:
        app: content-dep
    spec:
      containers:
      - name: content-dep
        image: thatcoldtoast/bird-api-content:0.0.4
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: NEO4J_URI
          valueFrom:
            secretKeyRef:
              key: neo4j_uri
        - name: NEO4J_USERNAME
          valueFrom:
            secretKeyRef:
              key: neo4j_username
        - name: NEO4J_PASSWORD
          valueFrom:
            secretKeyRef:
              key: neo4j_password
        - name: BCRYPT_LOG_ROUNDS
          valueFrom:
            secretKeyRef:
              key: neo4j_password
        - name: JWT_ACCESS_SECRET
          valueFrom:
            secretKeyRef:
              key: jwt_access_secret
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              key: jwt_refresh_secret
        - name: ENVIRONMENT
          valueFrom:
            secretKeyRef:
              key: environment
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              key: sentry_dsn
        - name: R2_URL
          valueFrom:
            secretKeyRef:
              key: r2_url
        - name: R2_SECRET
          valueFrom:
            secretKeyRef:
              key: r2_secret
        - name: R2_BUCKET_ID
          valueFrom:
            secretKeyRef:
              key: r2_bucket_id
